default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: db
  port: 5432
  pool: 5

development:
  <<: *default
  database: appeals_spring_development
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: db
  port: 5432
  pool: 5

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: appeals_sprint_test
  pool: 5

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: appeals_sprint_production
  pool: 5
